// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ModerationBans        string
	ModerationCases       string
	ModerationConfig      string
	ModerationConfigRoles string
	ModerationMutes       string
}{
	ModerationBans:        "moderation_bans",
	ModerationCases:       "moderation_cases",
	ModerationConfig:      "moderation_config",
	ModerationConfigRoles: "moderation_config_roles",
	ModerationMutes:       "moderation_mutes",
}
