name: asbwig

volumes:
  db:

networks:
  default:

services:
  app:
    container_name: asbwig-app
    image: Ranger-4297/asbwig:latest
    restart: unless-stopped
    networks:
      - default
    env_file:
      - app.env
    depends_on:
      - db
  db:
    container_name: asbwig-postgres-db
    image: postgres:16
    restart: no
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env